import { Question } from "@/types";

export const MOCK_QUESTIONS: Question[] = [
    // LEVEL 1 (Basic)
    {
        id: "l1-1",
        text: "What does HTML stand for?",
        options: ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyper Text Makeup Language"],
        correctAnswer: 0,
        level: 1,
    },
    {
        id: "l1-2",
        text: "Which HTML tag is used to define an internal style sheet?",
        options: ["<script>", "<style>", "<css>", "<link>"],
        correctAnswer: 1,
        level: 1,
    },
    {
        id: "l1-3",
        text: "Which property is used to change the background color?",
        options: ["color", "bgcolor", "background-color", "backup-color"],
        correctAnswer: 2,
        level: 1,
    },
    {
        id: "l1-4",
        text: "How do you select an element with id 'demo'?",
        options: ["#demo", ".demo", "demo", "*demo"],
        correctAnswer: 0,
        level: 1,
    },
    {
        id: "l1-5",
        text: "What is the correct syntax for referring to an external script called 'xxx.js'?",
        options: ["<script href='xxx.js'>", "<script name='xxx.js'>", "<script src='xxx.js'>", "<script file='xxx.js'>"],
        correctAnswer: 2,
        level: 1,
    },
    {
        id: "l1-6",
        text: "Which character is used to indicate an end tag?",
        options: ["^", "<", "/", "*"],
        correctAnswer: 2,
        level: 1,
    },
    {
        id: "l1-7",
        text: "How do you write 'Hello World' in an alert box?",
        options: ["msg('Hello World')", "msgBox('Hello World')", "alert('Hello World')", "alertBox('Hello World')"],
        correctAnswer: 2,
        level: 1,
    },
    {
        id: "l1-8",
        text: "Which operator is used to assign a value to a variable?",
        options: ["*", "-", "=", "x"],
        correctAnswer: 2,
        level: 1,
    },
    {
        id: "l1-9",
        text: "Inside which HTML element do we put the JavaScript?",
        options: ["<scripting>", "<js>", "<javascript>", "<script>"],
        correctAnswer: 3,
        level: 1,
    },
    {
        id: "l1-10",
        text: "Which event occurs when the user clicks on an HTML element?",
        options: ["onchange", "onclick", "onmouseclick", "onmouseover"],
        correctAnswer: 1,
        level: 1,
    },

    // LEVEL 2 (Intermediate)
    {
        id: "l2-1",
        text: "What is the output of: console.log(typeof NaN)?",
        options: ["'number'", "'NaN'", "'undefined'", "'object'"],
        correctAnswer: 0,
        level: 2,
    },
    {
        id: "l2-2",
        text: "Which method removes the last element from an array?",
        options: ["shift()", "pop()", "push()", "unshift()"],
        correctAnswer: 1,
        level: 2,
    },
    {
        id: "l2-3",
        text: "What does CSS stand for?",
        options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"],
        correctAnswer: 1,
        level: 2,
    },
    {
        id: "l2-4",
        text: "Which HTML attribute is used to specify an alternate text for an image?",
        options: ["title", "src", "href", "alt"],
        correctAnswer: 3,
        level: 2,
    },
    {
        id: "l2-5",
        text: "How do you create a function in JavaScript?",
        options: ["function:myFunction()", "function = myFunction()", "function myFunction()", "myFunction():function"],
        correctAnswer: 2,
        level: 2,
    },
    {
        id: "l2-6",
        text: "How do you call a function named 'myFunction'?",
        options: ["call myFunction()", "call function myFunction()", "myFunction()", "Call.myFunction()"],
        correctAnswer: 2,
        level: 2,
    },
    {
        id: "l2-7",
        text: "What is the correct way to write a JavaScript array?",
        options: ["var colors = (1:'red', 2:'green', 3:'blue')", "var colors = ['red', 'green', 'blue']", "var colors = 'red', 'green', 'blue'", "var colors = 1 = ('red'), 2 = ('green'), 3 = ('blue')"],
        correctAnswer: 1,
        level: 2,
    },
    {
        id: "l2-8",
        text: "Which JavaScript operator is used to check for both value and type equality?",
        options: ["==", "===", "=", "!="],
        correctAnswer: 1,
        level: 2,
    },
    {
        id: "l2-9",
        text: "What keyword is used to declare a block-scoped variable?",
        options: ["var", "let", "const", "Both let and const"],
        correctAnswer: 3,
        level: 2,
    },
    {
        id: "l2-10",
        text: "Which built-in method returns the length of the string?",
        options: ["length()", "size()", "index()", "None of the above"],
        correctAnswer: 3, // string.length is a property, not a method
        level: 2,
    },

    // LEVEL 3 (Advanced)
    {
        id: "l3-1",
        text: "What is the result of '2' + 2 in JavaScript?",
        options: ["4", "22", "NaN", "Error"],
        correctAnswer: 1,
        level: 3,
    },
    {
        id: "l3-2",
        text: "Which of the following is NOT a JavaScript data type?",
        options: ["Undefined", "Number", "Boolean", "Float"],
        correctAnswer: 3,
        level: 3,
    },
    {
        id: "l3-3",
        text: "What acts as the entry point for a Next.js application?",
        options: ["index.js", "app.js", "layout.tsx (in App Router)", "server.js"],
        correctAnswer: 2,
        level: 3,
    },
    {
        id: "l3-4",
        text: "Which hook is used for side effects in React?",
        options: ["useState", "useEffect", "useContext", "useReducer"],
        correctAnswer: 1,
        level: 3,
    },
    {
        id: "l3-5",
        text: "What is the purpose of the 'z-index' property in CSS?",
        options: ["Sets the width", "Sets the stack order", "Sets the opacity", "Sets the zoom level"],
        correctAnswer: 1,
        level: 3,
    },
    {
        id: "l3-6",
        text: "What does JSON stand for?",
        options: ["JavaScript Object Notation", "JavaScript Online Notation", "Java Syntax Object Notation", "Java Standard Object Notation"],
        correctAnswer: 0,
        level: 3,
    },
    {
        id: "l3-7",
        text: "Which method converts a JSON string into a JavaScript object?",
        options: ["JSON.stringify()", "JSON.parse()", "JSON.toObj()", "JSON.convert()"],
        correctAnswer: 1,
        level: 3,
    },
    {
        id: "l3-8",
        text: "What is the default display value for a <div> element?",
        options: ["inline", "block", "inline-block", "flex"],
        correctAnswer: 1,
        level: 3,
    },
    {
        id: "l3-9",
        text: "Which concept allows a child component to receive data from a parent component?",
        options: ["State", "Props", "Context", "Hooks"],
        correctAnswer: 1,
        level: 3,
    },
    {
        id: "l3-10",
        text: "What is the Virtual DOM?",
        options: ["A direct copy of the real DOM", "A lightweight copy of the DOM kept in memory", "A database for DOM elements", "A browser plugin"],
        correctAnswer: 1,
        level: 3,
    },
];
